#!/usr/bin/env node

/*
 *  advanced
 *
 */


fs = require("fs");
cui = require("../lib/cui");


cui.push({
	title: "Pick a file:",
	type: "buttons",
	main: function (cb) {
		fs.readdir(process.cwd(), function (err, filenames) {
			cb(err, filenames);
		});
	}
});

cui.push({
  title: "Pick an action:",
  type: "buttons",
	main: [
	  "Stat",
	  "Rename"
	]
});

cui.push(function (cb) {
  var last = cui.history.slice(-1)[0]
  cui.push((last === "Stat") ? statAction : renameInput);
  cb();
});

var statAction = function () {
	fs.stat(cui.history[0], function (err, data) {
		console.log(data || err);
	});
};


var renameInput = {
  type: "fields",
  main: function (cb) {
    cui.push(renameAction);
    var filename = cui.history[0];
    cb(null, "Type a new name for " + filename + ": ");
  }
};

var renameAction = function () {
  fs.rename(cui.history[0], cui.history[3], function (err) {
    console.log((err) ? err : cui.history[0] + " successfully renamed as " + cui.history[3]);
  });
};
