#!/usr/bin/env node

/*
 *  all
 *
 */

var fs = require('fs')
var cui = require('../')

cui.push({
  title: 'Try an example:',
  type: 'buttons',
  data: function(cb) {
    fs.readdir(__dirname, function(err, examples) {
      filtered = []
      examples.forEach(function(filename) { 
        if (filename !== 'all') {
          filtered.push(filename)
        }
      })
      cb(err, filtered)
    })
  }
})

cui.push(function(cb) {
  var example = __dirname + '/' + cui.last(1)
  cui.results = [] // effectively reset cui's state - should reset be a method?
  require(example)
  cb()
})
