#!/usr/bin/env node

/*
 *  basic
 *
 */


var cui = require("../lib/cui");


cui.push({
  title: "This is a very basic example.",
  type: "buttons",
  data: [
    "One",
    "Two",
    "Three"
  ],
  action: function () {
    console.log("You could do something now with: \"" + cui.results[0] + "\"");
  }
});
