#!/usr/bin/env node

console.log("This only works on OS X for now!");

var exec = require("child_process").exec

require("../lib/operator")({
  type: "sequence",
  data: [
    {
      type: "question",
      data: "type a few words: "
    }, {
      prompt: "pick a voice:",
      type: "choice",
      data: function (cb) {
        var s = exec("say -v ?");
        var voices = "";
        s.on("data", function (d) { voices += d });
        s.on("exit", function () {
          voices = voices.split("\n");
          voices = voices.map(function (v) { return v.split("  ")[0] });
          cb(null, voices);
        });
      }
    }, {
      type: "executable",
      data: function () {
        exec("say -v " + operator.results.slice(-1) + " " + operator.results[0]);
      }
    }
  ]
});
